/**
 * Split-It!
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("AccountApi", () => {
  let instance: api.AccountApi
  beforeEach(function() {
    instance = new api.AccountApi(config)
  });

  test("apiAccountLoginPost", () => {
    const body: api.LoginDto = undefined
    return expect(instance.apiAccountLoginPost(body, {})).resolves.toBe(null)
  })
  test("apiAccountLogoutPost", () => {
    return expect(instance.apiAccountLogoutPost({})).resolves.toBe(null)
  })
  test("apiAccountMfaMfaStringPost", () => {
    const mfaString: string = "mfaString_example"
    return expect(instance.apiAccountMfaMfaStringPost(mfaString, {})).resolves.toBe(null)
  })
  test("apiAccountRegisterPost", () => {
    const body: api.RegisterDto = undefined
    return expect(instance.apiAccountRegisterPost(body, {})).resolves.toBe(null)
  })
})

describe("BillApi", () => {
  let instance: api.BillApi
  beforeEach(function() {
    instance = new api.BillApi(config)
  });

  test("apiBillAcceptBillIdPost", () => {
    const billId: string = "38400000-8cf0-11bd-b23e-10b96e4ef00d"
    return expect(instance.apiBillAcceptBillIdPost(billId, {})).resolves.toBe(null)
  })
  test("apiBillBillIdDelete", () => {
    const billId: string = "38400000-8cf0-11bd-b23e-10b96e4ef00d"
    return expect(instance.apiBillBillIdDelete(billId, {})).resolves.toBe(null)
  })
  test("apiBillBillIdGet", () => {
    const billId: string = "38400000-8cf0-11bd-b23e-10b96e4ef00d"
    return expect(instance.apiBillBillIdGet(billId, {})).resolves.toBe(null)
  })
  test("apiBillBillIdPut", () => {
    const billId: string = "38400000-8cf0-11bd-b23e-10b96e4ef00d"
    const body: api.BillDto = undefined
    return expect(instance.apiBillBillIdPut(billId, body, {})).resolves.toBe(null)
  })
  test("apiBillGetmanyGet", () => {
    const body: api.BillFilter = undefined
    return expect(instance.apiBillGetmanyGet(body, {})).resolves.toBe(null)
  })
  test("apiBillPost", () => {
    const body: api.BillDto = undefined
    return expect(instance.apiBillPost(body, {})).resolves.toBe(null)
  })
  test("apiBillRejectBillIdPost", () => {
    const billId: string = "38400000-8cf0-11bd-b23e-10b96e4ef00d"
    return expect(instance.apiBillRejectBillIdPost(billId, {})).resolves.toBe(null)
  })
  test("billsGet", () => {
    return expect(instance.billsGet({})).resolves.toBe(null)
  })
  test("createGet", () => {
    return expect(instance.createGet({})).resolves.toBe(null)
  })
  test("usersGet", () => {
    return expect(instance.usersGet({})).resolves.toBe(null)
  })
})

describe("UserApi", () => {
  let instance: api.UserApi
  beforeEach(function() {
    instance = new api.UserApi(config)
  });

  test("apiUserGet", () => {
    const sortBy: UserSort = undefined
    const email: string = "email_example"
    const firstname: string = "firstname_example"
    const lastname: string = "lastname_example"
    const take: number = 56
    const skip: number = 56
    return expect(instance.apiUserGet(sortBy, email, firstname, lastname, take, skip, {})).resolves.toBe(null)
  })
  test("apiUserUserIdGet", () => {
    const userId: string = "38400000-8cf0-11bd-b23e-10b96e4ef00d"
    return expect(instance.apiUserUserIdGet(userId, {})).resolves.toBe(null)
  })
})

