/* tslint:disable */
/* eslint-disable */
/**
 * Split-It!
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { BillInputDto } from '../models';
import { CommentDto } from '../models';
import { CommentInputDto } from '../models';
import { CommentSort } from '../models';
import { DetailedBillDto } from '../models';
import { PayDto } from '../models';
import { SimpleBillDto } from '../models';
import { SimpleBillInputDto } from '../models';
/**
 * BillApi - axios parameter creator
 * @export
 */
export const BillApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} billId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBillBillIdAcceptPost: async (billId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'billId' is not null or undefined
            if (billId === null || billId === undefined) {
                throw new RequiredError('billId','Required parameter billId was null or undefined when calling apiBillBillIdAcceptPost.');
            }
            const localVarPath = `/api/Bill/{bill_id}/accept`
                .replace(`{${"bill_id"}}`, encodeURIComponent(String(billId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Token required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Token")
                    : await configuration.apiKey;
                localVarHeaderParameter["Token"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} billId 
         * @param {string} attachmentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBillBillIdAttachmentAttachmentIdDelete: async (billId: string, attachmentId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'billId' is not null or undefined
            if (billId === null || billId === undefined) {
                throw new RequiredError('billId','Required parameter billId was null or undefined when calling apiBillBillIdAttachmentAttachmentIdDelete.');
            }
            // verify required parameter 'attachmentId' is not null or undefined
            if (attachmentId === null || attachmentId === undefined) {
                throw new RequiredError('attachmentId','Required parameter attachmentId was null or undefined when calling apiBillBillIdAttachmentAttachmentIdDelete.');
            }
            const localVarPath = `/api/Bill/{BillId}/attachment/{AttachmentId}`
                .replace(`{${"BillId"}}`, encodeURIComponent(String(billId)))
                .replace(`{${"AttachmentId"}}`, encodeURIComponent(String(attachmentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Token required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Token")
                    : await configuration.apiKey;
                localVarHeaderParameter["Token"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} billId 
         * @param {string} attachmentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBillBillIdAttachmentAttachmentIdGet: async (billId: string, attachmentId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'billId' is not null or undefined
            if (billId === null || billId === undefined) {
                throw new RequiredError('billId','Required parameter billId was null or undefined when calling apiBillBillIdAttachmentAttachmentIdGet.');
            }
            // verify required parameter 'attachmentId' is not null or undefined
            if (attachmentId === null || attachmentId === undefined) {
                throw new RequiredError('attachmentId','Required parameter attachmentId was null or undefined when calling apiBillBillIdAttachmentAttachmentIdGet.');
            }
            const localVarPath = `/api/Bill/{BillId}/attachment/{AttachmentId}`
                .replace(`{${"BillId"}}`, encodeURIComponent(String(billId)))
                .replace(`{${"AttachmentId"}}`, encodeURIComponent(String(attachmentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Token required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Token")
                    : await configuration.apiKey;
                localVarHeaderParameter["Token"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} billId 
         * @param {Blob} [file] 
         * @param {string} [caption] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBillBillIdAttachmentPostForm: async (billId: string, file?: Blob, caption?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'billId' is not null or undefined
            if (billId === null || billId === undefined) {
                throw new RequiredError('billId','Required parameter billId was null or undefined when calling apiBillBillIdAttachmentPostForm.');
            }
            const localVarPath = `/api/Bill/{BillId}/attachment`
                .replace(`{${"BillId"}}`, encodeURIComponent(String(billId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new FormData();

            // authentication Token required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Token")
                    : await configuration.apiKey;
                localVarHeaderParameter["Token"] = localVarApiKeyValue;
            }


            if (file !== undefined) { 
                localVarFormParams.append('File', file as any);
            }

            if (caption !== undefined) { 
                localVarFormParams.append('Caption', caption as any);
            }

            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get one comment from a bill
         * @param {string} billId 
         * @param {string} commentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBillBillIdCommentsCommentIdGet: async (billId: string, commentId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'billId' is not null or undefined
            if (billId === null || billId === undefined) {
                throw new RequiredError('billId','Required parameter billId was null or undefined when calling apiBillBillIdCommentsCommentIdGet.');
            }
            // verify required parameter 'commentId' is not null or undefined
            if (commentId === null || commentId === undefined) {
                throw new RequiredError('commentId','Required parameter commentId was null or undefined when calling apiBillBillIdCommentsCommentIdGet.');
            }
            const localVarPath = `/api/Bill/{BillId}/comments/{CommentId}`
                .replace(`{${"BillId"}}`, encodeURIComponent(String(billId)))
                .replace(`{${"CommentId"}}`, encodeURIComponent(String(commentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Token required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Token")
                    : await configuration.apiKey;
                localVarHeaderParameter["Token"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get many comments from a bill
         * @param {string} billId 
         * @param {CommentSort} [sortBy] 
         * @param {number} [take] 
         * @param {number} [skip] 
         * @param {string} [content] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBillBillIdCommentsGet: async (billId: string, sortBy?: CommentSort, take?: number, skip?: number, content?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'billId' is not null or undefined
            if (billId === null || billId === undefined) {
                throw new RequiredError('billId','Required parameter billId was null or undefined when calling apiBillBillIdCommentsGet.');
            }
            const localVarPath = `/api/Bill/{BillId}/comments`
                .replace(`{${"BillId"}}`, encodeURIComponent(String(billId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Token required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Token")
                    : await configuration.apiKey;
                localVarHeaderParameter["Token"] = localVarApiKeyValue;
            }

            if (sortBy !== undefined) {
                localVarQueryParameter['sortBy'] = sortBy;
            }

            if (take !== undefined) {
                localVarQueryParameter['take'] = take;
            }

            if (skip !== undefined) {
                localVarQueryParameter['skip'] = skip;
            }

            if (content !== undefined) {
                localVarQueryParameter['content'] = content;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create a comment on a bill
         * @param {string} billId 
         * @param {CommentInputDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBillBillIdCommentsPost: async (billId: string, body?: CommentInputDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'billId' is not null or undefined
            if (billId === null || billId === undefined) {
                throw new RequiredError('billId','Required parameter billId was null or undefined when calling apiBillBillIdCommentsPost.');
            }
            const localVarPath = `/api/Bill/{BillId}/comments`
                .replace(`{${"BillId"}}`, encodeURIComponent(String(billId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Token required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Token")
                    : await configuration.apiKey;
                localVarHeaderParameter["Token"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers?.['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} billId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBillBillIdDelete: async (billId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'billId' is not null or undefined
            if (billId === null || billId === undefined) {
                throw new RequiredError('billId','Required parameter billId was null or undefined when calling apiBillBillIdDelete.');
            }
            const localVarPath = `/api/Bill/{bill_id}`
                .replace(`{${"bill_id"}}`, encodeURIComponent(String(billId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Token required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Token")
                    : await configuration.apiKey;
                localVarHeaderParameter["Token"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Use this route to get a bill. Pass in bill guid
         * @summary Get Bill
         * @param {string} billId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBillBillIdGet: async (billId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'billId' is not null or undefined
            if (billId === null || billId === undefined) {
                throw new RequiredError('billId','Required parameter billId was null or undefined when calling apiBillBillIdGet.');
            }
            const localVarPath = `/api/Bill/{bill_id}`
                .replace(`{${"bill_id"}}`, encodeURIComponent(String(billId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Token required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Token")
                    : await configuration.apiKey;
                localVarHeaderParameter["Token"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary If the user has the bill id they can join it. This makes sharing by link and QR possible
         * @param {string} billId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBillBillIdJoinPost: async (billId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'billId' is not null or undefined
            if (billId === null || billId === undefined) {
                throw new RequiredError('billId','Required parameter billId was null or undefined when calling apiBillBillIdJoinPost.');
            }
            const localVarPath = `/api/Bill/{bill_id}/join`
                .replace(`{${"bill_id"}}`, encodeURIComponent(String(billId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Token required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Token")
                    : await configuration.apiKey;
                localVarHeaderParameter["Token"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} billId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBillBillIdPayGet: async (billId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'billId' is not null or undefined
            if (billId === null || billId === undefined) {
                throw new RequiredError('billId','Required parameter billId was null or undefined when calling apiBillBillIdPayGet.');
            }
            const localVarPath = `/api/Bill/{bill_id}/pay`
                .replace(`{${"bill_id"}}`, encodeURIComponent(String(billId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Token required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Token")
                    : await configuration.apiKey;
                localVarHeaderParameter["Token"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Use this route to edit a bill. Quite similar to the create bill. To edit just do the same.
         * @summary Edit a bill
         * @param {string} billId 
         * @param {BillInputDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBillBillIdPut: async (billId: string, body?: BillInputDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'billId' is not null or undefined
            if (billId === null || billId === undefined) {
                throw new RequiredError('billId','Required parameter billId was null or undefined when calling apiBillBillIdPut.');
            }
            const localVarPath = `/api/Bill/{bill_id}`
                .replace(`{${"bill_id"}}`, encodeURIComponent(String(billId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Token required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Token")
                    : await configuration.apiKey;
                localVarHeaderParameter["Token"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers?.['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Re-invite user to the bill if they rejected it
         * @param {string} billId 
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBillBillIdReinviteUserIdPost: async (billId: string, userId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'billId' is not null or undefined
            if (billId === null || billId === undefined) {
                throw new RequiredError('billId','Required parameter billId was null or undefined when calling apiBillBillIdReinviteUserIdPost.');
            }
            // verify required parameter 'userId' is not null or undefined
            if (userId === null || userId === undefined) {
                throw new RequiredError('userId','Required parameter userId was null or undefined when calling apiBillBillIdReinviteUserIdPost.');
            }
            const localVarPath = `/api/Bill/{BillId}/reinvite/{UserId}`
                .replace(`{${"BillId"}}`, encodeURIComponent(String(billId)))
                .replace(`{${"UserId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Token required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Token")
                    : await configuration.apiKey;
                localVarHeaderParameter["Token"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} billId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBillBillIdRejectPost: async (billId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'billId' is not null or undefined
            if (billId === null || billId === undefined) {
                throw new RequiredError('billId','Required parameter billId was null or undefined when calling apiBillBillIdRejectPost.');
            }
            const localVarPath = `/api/Bill/{bill_id}/reject`
                .replace(`{${"bill_id"}}`, encodeURIComponent(String(billId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Token required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Token")
                    : await configuration.apiKey;
                localVarHeaderParameter["Token"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Use this route to search bills.
         * @summary Find bills
         * @param {number} [startTime] 
         * @param {number} [endTime] 
         * @param {string} [billOwner] 
         * @param {Array<string>} [billMembers] 
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {boolean} [isSettled] 
         * @param {string} [title] 
         * @param {number} [minAmount] 
         * @param {number} [maxAmount] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBillGet: async (startTime?: number, endTime?: number, billOwner?: string, billMembers?: Array<string>, limit?: number, offset?: number, isSettled?: boolean, title?: string, minAmount?: number, maxAmount?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Bill`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Token required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Token")
                    : await configuration.apiKey;
                localVarHeaderParameter["Token"] = localVarApiKeyValue;
            }

            if (startTime !== undefined) {
                localVarQueryParameter['StartTime'] = startTime;
            }

            if (endTime !== undefined) {
                localVarQueryParameter['EndTime'] = endTime;
            }

            if (billOwner !== undefined) {
                localVarQueryParameter['BillOwner'] = billOwner;
            }

            if (billMembers) {
                localVarQueryParameter['BillMembers'] = billMembers;
            }

            if (limit !== undefined) {
                localVarQueryParameter['Limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['Offset'] = offset;
            }

            if (isSettled !== undefined) {
                localVarQueryParameter['IsSettled'] = isSettled;
            }

            if (title !== undefined) {
                localVarQueryParameter['Title'] = title;
            }

            if (minAmount !== undefined) {
                localVarQueryParameter['MinAmount'] = minAmount;
            }

            if (maxAmount !== undefined) {
                localVarQueryParameter['MaxAmount'] = maxAmount;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Use this route to create a bill.
         * @summary Create Bill
         * @param {BillInputDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBillPost: async (body?: BillInputDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Bill`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Token required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Token")
                    : await configuration.apiKey;
                localVarHeaderParameter["Token"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers?.['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Use this route to create a simple bill.
         * @summary Create Bill Simple
         * @param {SimpleBillInputDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBillSimplePost: async (body?: SimpleBillInputDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Bill/simple`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Token required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Token")
                    : await configuration.apiKey;
                localVarHeaderParameter["Token"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers?.['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BillApi - functional programming interface
 * @export
 */
export const BillApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} billId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBillBillIdAcceptPost(billId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await BillApiAxiosParamCreator(configuration).apiBillBillIdAcceptPost(billId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {string} billId 
         * @param {string} attachmentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBillBillIdAttachmentAttachmentIdDelete(billId: string, attachmentId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await BillApiAxiosParamCreator(configuration).apiBillBillIdAttachmentAttachmentIdDelete(billId, attachmentId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {string} billId 
         * @param {string} attachmentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBillBillIdAttachmentAttachmentIdGet(billId: string, attachmentId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await BillApiAxiosParamCreator(configuration).apiBillBillIdAttachmentAttachmentIdGet(billId, attachmentId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {string} billId 
         * @param {Blob} [file] 
         * @param {string} [caption] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBillBillIdAttachmentPostForm(billId: string, file?: Blob, caption?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await BillApiAxiosParamCreator(configuration).apiBillBillIdAttachmentPostForm(billId, file, caption, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get one comment from a bill
         * @param {string} billId 
         * @param {string} commentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBillBillIdCommentsCommentIdGet(billId: string, commentId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<CommentDto>>> {
            const localVarAxiosArgs = await BillApiAxiosParamCreator(configuration).apiBillBillIdCommentsCommentIdGet(billId, commentId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get many comments from a bill
         * @param {string} billId 
         * @param {CommentSort} [sortBy] 
         * @param {number} [take] 
         * @param {number} [skip] 
         * @param {string} [content] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBillBillIdCommentsGet(billId: string, sortBy?: CommentSort, take?: number, skip?: number, content?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<CommentDto>>>> {
            const localVarAxiosArgs = await BillApiAxiosParamCreator(configuration).apiBillBillIdCommentsGet(billId, sortBy, take, skip, content, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Create a comment on a bill
         * @param {string} billId 
         * @param {CommentInputDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBillBillIdCommentsPost(billId: string, body?: CommentInputDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<CommentDto>>> {
            const localVarAxiosArgs = await BillApiAxiosParamCreator(configuration).apiBillBillIdCommentsPost(billId, body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {string} billId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBillBillIdDelete(billId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await BillApiAxiosParamCreator(configuration).apiBillBillIdDelete(billId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Use this route to get a bill. Pass in bill guid
         * @summary Get Bill
         * @param {string} billId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBillBillIdGet(billId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<DetailedBillDto>>> {
            const localVarAxiosArgs = await BillApiAxiosParamCreator(configuration).apiBillBillIdGet(billId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary If the user has the bill id they can join it. This makes sharing by link and QR possible
         * @param {string} billId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBillBillIdJoinPost(billId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await BillApiAxiosParamCreator(configuration).apiBillBillIdJoinPost(billId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {string} billId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBillBillIdPayGet(billId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<PayDto>>> {
            const localVarAxiosArgs = await BillApiAxiosParamCreator(configuration).apiBillBillIdPayGet(billId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Use this route to edit a bill. Quite similar to the create bill. To edit just do the same.
         * @summary Edit a bill
         * @param {string} billId 
         * @param {BillInputDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBillBillIdPut(billId: string, body?: BillInputDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<DetailedBillDto>>> {
            const localVarAxiosArgs = await BillApiAxiosParamCreator(configuration).apiBillBillIdPut(billId, body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Re-invite user to the bill if they rejected it
         * @param {string} billId 
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBillBillIdReinviteUserIdPost(billId: string, userId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await BillApiAxiosParamCreator(configuration).apiBillBillIdReinviteUserIdPost(billId, userId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {string} billId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBillBillIdRejectPost(billId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await BillApiAxiosParamCreator(configuration).apiBillBillIdRejectPost(billId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Use this route to search bills.
         * @summary Find bills
         * @param {number} [startTime] 
         * @param {number} [endTime] 
         * @param {string} [billOwner] 
         * @param {Array<string>} [billMembers] 
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {boolean} [isSettled] 
         * @param {string} [title] 
         * @param {number} [minAmount] 
         * @param {number} [maxAmount] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBillGet(startTime?: number, endTime?: number, billOwner?: string, billMembers?: Array<string>, limit?: number, offset?: number, isSettled?: boolean, title?: string, minAmount?: number, maxAmount?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<SimpleBillDto>>>> {
            const localVarAxiosArgs = await BillApiAxiosParamCreator(configuration).apiBillGet(startTime, endTime, billOwner, billMembers, limit, offset, isSettled, title, minAmount, maxAmount, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Use this route to create a bill.
         * @summary Create Bill
         * @param {BillInputDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBillPost(body?: BillInputDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<DetailedBillDto>>> {
            const localVarAxiosArgs = await BillApiAxiosParamCreator(configuration).apiBillPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Use this route to create a simple bill.
         * @summary Create Bill Simple
         * @param {SimpleBillInputDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBillSimplePost(body?: SimpleBillInputDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<DetailedBillDto>>> {
            const localVarAxiosArgs = await BillApiAxiosParamCreator(configuration).apiBillSimplePost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * BillApi - factory interface
 * @export
 */
export const BillApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {string} billId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBillBillIdAcceptPost(billId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return BillApiFp(configuration).apiBillBillIdAcceptPost(billId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} billId 
         * @param {string} attachmentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBillBillIdAttachmentAttachmentIdDelete(billId: string, attachmentId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return BillApiFp(configuration).apiBillBillIdAttachmentAttachmentIdDelete(billId, attachmentId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} billId 
         * @param {string} attachmentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBillBillIdAttachmentAttachmentIdGet(billId: string, attachmentId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return BillApiFp(configuration).apiBillBillIdAttachmentAttachmentIdGet(billId, attachmentId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} billId 
         * @param {Blob} [file] 
         * @param {string} [caption] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBillBillIdAttachmentPostForm(billId: string, file?: Blob, caption?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return BillApiFp(configuration).apiBillBillIdAttachmentPostForm(billId, file, caption, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get one comment from a bill
         * @param {string} billId 
         * @param {string} commentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBillBillIdCommentsCommentIdGet(billId: string, commentId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<CommentDto>> {
            return BillApiFp(configuration).apiBillBillIdCommentsCommentIdGet(billId, commentId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get many comments from a bill
         * @param {string} billId 
         * @param {CommentSort} [sortBy] 
         * @param {number} [take] 
         * @param {number} [skip] 
         * @param {string} [content] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBillBillIdCommentsGet(billId: string, sortBy?: CommentSort, take?: number, skip?: number, content?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Array<CommentDto>>> {
            return BillApiFp(configuration).apiBillBillIdCommentsGet(billId, sortBy, take, skip, content, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create a comment on a bill
         * @param {string} billId 
         * @param {CommentInputDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBillBillIdCommentsPost(billId: string, body?: CommentInputDto, options?: AxiosRequestConfig): Promise<AxiosResponse<CommentDto>> {
            return BillApiFp(configuration).apiBillBillIdCommentsPost(billId, body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} billId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBillBillIdDelete(billId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return BillApiFp(configuration).apiBillBillIdDelete(billId, options).then((request) => request(axios, basePath));
        },
        /**
         * Use this route to get a bill. Pass in bill guid
         * @summary Get Bill
         * @param {string} billId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBillBillIdGet(billId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<DetailedBillDto>> {
            return BillApiFp(configuration).apiBillBillIdGet(billId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary If the user has the bill id they can join it. This makes sharing by link and QR possible
         * @param {string} billId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBillBillIdJoinPost(billId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return BillApiFp(configuration).apiBillBillIdJoinPost(billId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} billId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBillBillIdPayGet(billId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<PayDto>> {
            return BillApiFp(configuration).apiBillBillIdPayGet(billId, options).then((request) => request(axios, basePath));
        },
        /**
         * Use this route to edit a bill. Quite similar to the create bill. To edit just do the same.
         * @summary Edit a bill
         * @param {string} billId 
         * @param {BillInputDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBillBillIdPut(billId: string, body?: BillInputDto, options?: AxiosRequestConfig): Promise<AxiosResponse<DetailedBillDto>> {
            return BillApiFp(configuration).apiBillBillIdPut(billId, body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Re-invite user to the bill if they rejected it
         * @param {string} billId 
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBillBillIdReinviteUserIdPost(billId: string, userId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return BillApiFp(configuration).apiBillBillIdReinviteUserIdPost(billId, userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} billId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBillBillIdRejectPost(billId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return BillApiFp(configuration).apiBillBillIdRejectPost(billId, options).then((request) => request(axios, basePath));
        },
        /**
         * Use this route to search bills.
         * @summary Find bills
         * @param {number} [startTime] 
         * @param {number} [endTime] 
         * @param {string} [billOwner] 
         * @param {Array<string>} [billMembers] 
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {boolean} [isSettled] 
         * @param {string} [title] 
         * @param {number} [minAmount] 
         * @param {number} [maxAmount] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBillGet(startTime?: number, endTime?: number, billOwner?: string, billMembers?: Array<string>, limit?: number, offset?: number, isSettled?: boolean, title?: string, minAmount?: number, maxAmount?: number, options?: AxiosRequestConfig): Promise<AxiosResponse<Array<SimpleBillDto>>> {
            return BillApiFp(configuration).apiBillGet(startTime, endTime, billOwner, billMembers, limit, offset, isSettled, title, minAmount, maxAmount, options).then((request) => request(axios, basePath));
        },
        /**
         * Use this route to create a bill.
         * @summary Create Bill
         * @param {BillInputDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBillPost(body?: BillInputDto, options?: AxiosRequestConfig): Promise<AxiosResponse<DetailedBillDto>> {
            return BillApiFp(configuration).apiBillPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Use this route to create a simple bill.
         * @summary Create Bill Simple
         * @param {SimpleBillInputDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBillSimplePost(body?: SimpleBillInputDto, options?: AxiosRequestConfig): Promise<AxiosResponse<DetailedBillDto>> {
            return BillApiFp(configuration).apiBillSimplePost(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * BillApi - object-oriented interface
 * @export
 * @class BillApi
 * @extends {BaseAPI}
 */
export class BillApi extends BaseAPI {
    /**
     * 
     * @param {string} billId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillApi
     */
    public async apiBillBillIdAcceptPost(billId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return BillApiFp(this.configuration).apiBillBillIdAcceptPost(billId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {string} billId 
     * @param {string} attachmentId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillApi
     */
    public async apiBillBillIdAttachmentAttachmentIdDelete(billId: string, attachmentId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return BillApiFp(this.configuration).apiBillBillIdAttachmentAttachmentIdDelete(billId, attachmentId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {string} billId 
     * @param {string} attachmentId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillApi
     */
    public async apiBillBillIdAttachmentAttachmentIdGet(billId: string, attachmentId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return BillApiFp(this.configuration).apiBillBillIdAttachmentAttachmentIdGet(billId, attachmentId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {string} billId 
     * @param {Blob} [file] 
     * @param {string} [caption] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillApi
     */
    public async apiBillBillIdAttachmentPostForm(billId: string, file?: Blob, caption?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return BillApiFp(this.configuration).apiBillBillIdAttachmentPostForm(billId, file, caption, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Get one comment from a bill
     * @param {string} billId 
     * @param {string} commentId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillApi
     */
    public async apiBillBillIdCommentsCommentIdGet(billId: string, commentId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<CommentDto>> {
        return BillApiFp(this.configuration).apiBillBillIdCommentsCommentIdGet(billId, commentId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Get many comments from a bill
     * @param {string} billId 
     * @param {CommentSort} [sortBy] 
     * @param {number} [take] 
     * @param {number} [skip] 
     * @param {string} [content] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillApi
     */
    public async apiBillBillIdCommentsGet(billId: string, sortBy?: CommentSort, take?: number, skip?: number, content?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<CommentDto>>> {
        return BillApiFp(this.configuration).apiBillBillIdCommentsGet(billId, sortBy, take, skip, content, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Create a comment on a bill
     * @param {string} billId 
     * @param {CommentInputDto} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillApi
     */
    public async apiBillBillIdCommentsPost(billId: string, body?: CommentInputDto, options?: AxiosRequestConfig) : Promise<AxiosResponse<CommentDto>> {
        return BillApiFp(this.configuration).apiBillBillIdCommentsPost(billId, body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {string} billId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillApi
     */
    public async apiBillBillIdDelete(billId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return BillApiFp(this.configuration).apiBillBillIdDelete(billId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Use this route to get a bill. Pass in bill guid
     * @summary Get Bill
     * @param {string} billId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillApi
     */
    public async apiBillBillIdGet(billId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<DetailedBillDto>> {
        return BillApiFp(this.configuration).apiBillBillIdGet(billId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary If the user has the bill id they can join it. This makes sharing by link and QR possible
     * @param {string} billId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillApi
     */
    public async apiBillBillIdJoinPost(billId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return BillApiFp(this.configuration).apiBillBillIdJoinPost(billId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {string} billId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillApi
     */
    public async apiBillBillIdPayGet(billId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<PayDto>> {
        return BillApiFp(this.configuration).apiBillBillIdPayGet(billId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Use this route to edit a bill. Quite similar to the create bill. To edit just do the same.
     * @summary Edit a bill
     * @param {string} billId 
     * @param {BillInputDto} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillApi
     */
    public async apiBillBillIdPut(billId: string, body?: BillInputDto, options?: AxiosRequestConfig) : Promise<AxiosResponse<DetailedBillDto>> {
        return BillApiFp(this.configuration).apiBillBillIdPut(billId, body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Re-invite user to the bill if they rejected it
     * @param {string} billId 
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillApi
     */
    public async apiBillBillIdReinviteUserIdPost(billId: string, userId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return BillApiFp(this.configuration).apiBillBillIdReinviteUserIdPost(billId, userId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {string} billId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillApi
     */
    public async apiBillBillIdRejectPost(billId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return BillApiFp(this.configuration).apiBillBillIdRejectPost(billId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Use this route to search bills.
     * @summary Find bills
     * @param {number} [startTime] 
     * @param {number} [endTime] 
     * @param {string} [billOwner] 
     * @param {Array<string>} [billMembers] 
     * @param {number} [limit] 
     * @param {number} [offset] 
     * @param {boolean} [isSettled] 
     * @param {string} [title] 
     * @param {number} [minAmount] 
     * @param {number} [maxAmount] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillApi
     */
    public async apiBillGet(startTime?: number, endTime?: number, billOwner?: string, billMembers?: Array<string>, limit?: number, offset?: number, isSettled?: boolean, title?: string, minAmount?: number, maxAmount?: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<SimpleBillDto>>> {
        return BillApiFp(this.configuration).apiBillGet(startTime, endTime, billOwner, billMembers, limit, offset, isSettled, title, minAmount, maxAmount, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Use this route to create a bill.
     * @summary Create Bill
     * @param {BillInputDto} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillApi
     */
    public async apiBillPost(body?: BillInputDto, options?: AxiosRequestConfig) : Promise<AxiosResponse<DetailedBillDto>> {
        return BillApiFp(this.configuration).apiBillPost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Use this route to create a simple bill.
     * @summary Create Bill Simple
     * @param {SimpleBillInputDto} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillApi
     */
    public async apiBillSimplePost(body?: SimpleBillInputDto, options?: AxiosRequestConfig) : Promise<AxiosResponse<DetailedBillDto>> {
        return BillApiFp(this.configuration).apiBillSimplePost(body, options).then((request) => request(this.axios, this.basePath));
    }
}
