/* tslint:disable */
/* eslint-disable */
/**
 * Split-It!
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface BillFilter
 */
export interface BillFilter {
    /**
     * 
     * @type {number}
     * @memberof BillFilter
     */
    startTime?: number;
    /**
     * 
     * @type {number}
     * @memberof BillFilter
     */
    endTime?: number;
    /**
     * 
     * @type {string}
     * @memberof BillFilter
     */
    billOwner?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof BillFilter
     */
    billMembers?: Array<string> | null;
    /**
     * 
     * @type {number}
     * @memberof BillFilter
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof BillFilter
     */
    offset?: number;
    /**
     * 
     * @type {boolean}
     * @memberof BillFilter
     */
    isSettled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof BillFilter
     */
    title?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BillFilter
     */
    startAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof BillFilter
     */
    endAmount?: number;
}
