/* tslint:disable */
/* eslint-disable */
/**
 * Split-It!
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ItemDto } from './item-dto';
import { ShareDto } from './share-dto';
/**
 * 
 * @export
 * @interface BillDto
 */
export interface BillDto {
    /**
     * 
     * @type {string}
     * @memberof BillDto
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof BillDto
     */
    created?: Date;
    /**
     * 
     * @type {string}
     * @memberof BillDto
     */
    ownerId?: string;
    /**
     * 
     * @type {number}
     * @memberof BillDto
     */
    total?: number;
    /**
     * 
     * @type {string}
     * @memberof BillDto
     */
    title: string;
    /**
     * 
     * @type {Array<ShareDto>}
     * @memberof BillDto
     */
    shares: Array<ShareDto>;
    /**
     * 
     * @type {Array<ItemDto>}
     * @memberof BillDto
     */
    overallItems?: Array<ItemDto> | null;
    /**
     * 
     * @type {boolean}
     * @memberof BillDto
     */
    isSettled?: boolean;
}
