/* tslint:disable */
/* eslint-disable */
/**
 * Split-It!
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ShareInputDto } from './share-input-dto';
/**
 * 
 * @export
 * @interface BillInputDto
 */
export interface BillInputDto {
    /**
     * 
     * @type {string}
     * @memberof BillInputDto
     */
    ownerId: string;
    /**
     * Defaults to current time
     * @type {Date}
     * @memberof BillInputDto
     */
    created?: Date;
    /**
     * 
     * @type {string}
     * @memberof BillInputDto
     */
    title: string;
    /**
     * 
     * @type {Array<ShareInputDto>}
     * @memberof BillInputDto
     */
    shares: Array<ShareInputDto>;
}
