/* tslint:disable */
/* eslint-disable */
/**
 * Split-It!
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface BillIdAttachmentBody
 */
export interface BillIdAttachmentBody {
    /**
     * 
     * @type {Blob}
     * @memberof BillIdAttachmentBody
     */
    file: Blob;
    /**
     * Defaults to file name if not provided
     * @type {string}
     * @memberof BillIdAttachmentBody
     */
    caption?: string | null;
}
