/* tslint:disable */
/* eslint-disable */
/**
 * Split-It!
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface BillSimpleDtoIn
 */
export interface BillSimpleDtoIn {
    /**
     * 
     * @type {string}
     * @memberof BillSimpleDtoIn
     */
    title: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof BillSimpleDtoIn
     */
    userIds: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof BillSimpleDtoIn
     */
    amount: number;
}
