/* tslint:disable */
/* eslint-disable */
/**
 * Split-It!
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CardDto
 */
export interface CardDto {
    /**
     * 
     * @type {string}
     * @memberof CardDto
     */
    number: string;
    /**
     * 
     * @type {string}
     * @memberof CardDto
     */
    secret: string;
    /**
     * 
     * @type {string}
     * @memberof CardDto
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof CardDto
     */
    expiry: Date;
    /**
     * 
     * @type {Date}
     * @memberof CardDto
     */
    doB: Date;
}
