/* tslint:disable */
/* eslint-disable */
/**
 * Split-It!
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UserInfoDto } from './user-info-dto';
/**
 * 
 * @export
 * @interface CommentDto
 */
export interface CommentDto {
    /**
     * 
     * @type {string}
     * @memberof CommentDto
     */
    id?: string;
    /**
     * 
     * @type {UserInfoDto}
     * @memberof CommentDto
     */
    commenter?: UserInfoDto;
    /**
     * 
     * @type {string}
     * @memberof CommentDto
     */
    content?: string | null;
}
