/* tslint:disable */
/* eslint-disable */
/**
 * Split-It!
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface DetailedItemDto
 */
export interface DetailedItemDto {
    /**
     * 
     * @type {string}
     * @memberof DetailedItemDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof DetailedItemDto
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof DetailedItemDto
     */
    price?: number;
}
