/* tslint:disable */
/* eslint-disable */
/**
 * Split-It!
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AttachmentDto } from './attachment-dto';
import { DetailedShareDto } from './detailed-share-dto';
import { UserInfoDto } from './user-info-dto';
/**
 * 
 * @export
 * @interface DetailedBillDto
 */
export interface DetailedBillDto {
    /**
     * 
     * @type {string}
     * @memberof DetailedBillDto
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof DetailedBillDto
     */
    created?: Date;
    /**
     * 
     * @type {UserInfoDto}
     * @memberof DetailedBillDto
     */
    owner?: UserInfoDto;
    /**
     * 
     * @type {number}
     * @memberof DetailedBillDto
     */
    total?: number;
    /**
     * 
     * @type {string}
     * @memberof DetailedBillDto
     */
    title?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof DetailedBillDto
     */
    isSettled?: boolean;
    /**
     * 
     * @type {Array<DetailedShareDto>}
     * @memberof DetailedBillDto
     */
    shares?: Array<DetailedShareDto> | null;
    /**
     * 
     * @type {Array<AttachmentDto>}
     * @memberof DetailedBillDto
     */
    attachments?: Array<AttachmentDto> | null;
}
