/* tslint:disable */
/* eslint-disable */
/**
 * Split-It!
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DetailedItemDto } from './detailed-item-dto';
import { UserInfoDto } from './user-info-dto';
/**
 * 
 * @export
 * @interface DetailedShareDto
 */
export interface DetailedShareDto {
    /**
     * 
     * @type {string}
     * @memberof DetailedShareDto
     */
    id?: string;
    /**
     * 
     * @type {boolean}
     * @memberof DetailedShareDto
     */
    hasPaid?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DetailedShareDto
     */
    hasRejected?: boolean;
    /**
     * 
     * @type {number}
     * @memberof DetailedShareDto
     */
    total?: number;
    /**
     * 
     * @type {UserInfoDto}
     * @memberof DetailedShareDto
     */
    payer?: UserInfoDto;
    /**
     * 
     * @type {Array<DetailedItemDto>}
     * @memberof DetailedShareDto
     */
    items?: Array<DetailedItemDto> | null;
}
