/* tslint:disable */
/* eslint-disable */
/**
 * Split-It!
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ForgottenPasswordSubmitDto
 */
export interface ForgottenPasswordSubmitDto {
    /**
     * 
     * @type {string}
     * @memberof ForgottenPasswordSubmitDto
     */
    secret: string;
    /**
     * 
     * @type {string}
     * @memberof ForgottenPasswordSubmitDto
     */
    password: string;
}
