/* tslint:disable */
/* eslint-disable */
/**
 * Split-It!
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GroupDto
 */
export interface GroupDto {
    /**
     * 
     * @type {string}
     * @memberof GroupDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof GroupDto
     */
    ownerId?: string;
    /**
     * 
     * @type {string}
     * @memberof GroupDto
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof GroupDto
     */
    memberIds: Array<string>;
}
