/* tslint:disable */
/* eslint-disable */
/**
 * Split-It!
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Notification entity and DTO
 * @export
 * @interface Notification
 */
export interface Notification {
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    id?: string;
    /**
     * UserId that this notification belongs to
     * @type {string}
     * @memberof Notification
     */
    userId?: string;
    /**
     * Guid of resource in the specified Domain
     * @type {string}
     * @memberof Notification
     */
    resourceId?: string;
    /**
     * Brief user friendly notification message
     * @type {string}
     * @memberof Notification
     */
    message?: string | null;
    /**
     * The 'route' that this notification belongs to
     * @type {string}
     * @memberof Notification
     */
    domain?: string | null;
    /**
     * Notification creation date
     * @type {Date}
     * @memberof Notification
     */
    createdAt: Date;
}
