/* tslint:disable */
/* eslint-disable */
/**
 * Split-It!
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ItemDto } from './item-dto';
/**
 * 
 * @export
 * @interface ShareDto
 */
export interface ShareDto {
    /**
     * 
     * @type {boolean}
     * @memberof ShareDto
     */
    hasPaid?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ShareDto
     */
    hasRejected?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ShareDto
     */
    total?: number;
    /**
     * 
     * @type {string}
     * @memberof ShareDto
     */
    payerId: string;
    /**
     * 
     * @type {Array<ItemDto>}
     * @memberof ShareDto
     */
    items: Array<ItemDto>;
    /**
     * 
     * @type {string}
     * @memberof ShareDto
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ShareDto
     */
    name?: string | null;
}
