/* tslint:disable */
/* eslint-disable */
/**
 * Split-It!
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ItemInputDto } from './item-input-dto';
import { Status } from './status';
/**
 * 
 * @export
 * @interface ShareInputDto
 */
export interface ShareInputDto {
    /**
     * 
     * @type {string}
     * @memberof ShareInputDto
     */
    payerId: string;
    /**
     * 
     * @type {Array<ItemInputDto>}
     * @memberof ShareInputDto
     */
    items: Array<ItemInputDto>;
    /**
     * 
     * @type {Status}
     * @memberof ShareInputDto
     */
    status?: Status;
}
