/* tslint:disable */
/* eslint-disable */
/**
 * Split-It!
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UserInfoDto } from './user-info-dto';
/**
 * 
 * @export
 * @interface SimpleGroupDto
 */
export interface SimpleGroupDto {
    /**
     * 
     * @type {string}
     * @memberof SimpleGroupDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof SimpleGroupDto
     */
    name?: string | null;
    /**
     * 
     * @type {UserInfoDto}
     * @memberof SimpleGroupDto
     */
    owner?: UserInfoDto;
    /**
     * 
     * @type {number}
     * @memberof SimpleGroupDto
     */
    memberCount?: number;
}
