/* tslint:disable */
/* eslint-disable */
/**
 * Split-It!
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UserInfoDto } from './user-info-dto';
/**
 * 
 * @export
 * @interface SimpleBillDto
 */
export interface SimpleBillDto {
    /**
     * 
     * @type {string}
     * @memberof SimpleBillDto
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof SimpleBillDto
     */
    created?: Date;
    /**
     * 
     * @type {UserInfoDto}
     * @memberof SimpleBillDto
     */
    owner?: UserInfoDto;
    /**
     * 
     * @type {number}
     * @memberof SimpleBillDto
     */
    total?: number;
    /**
     * 
     * @type {string}
     * @memberof SimpleBillDto
     */
    title?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof SimpleBillDto
     */
    isSettled?: boolean;
}
