/* tslint:disable */
/* eslint-disable */
/**
 * Split-It!
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @enum {string}
 */
export enum UserSort {
    EMAILASC = 'EMAIL_ASC',
    EMAILDESC = 'EMAIL_DESC',
    FIRSTNAMEASC = 'FIRSTNAME_ASC',
    FIRSTNAMEDESC = 'FIRSTNAME_DESC',
    LASTNAMEASC = 'LASTNAME_ASC',
    LASTNAMEDESC = 'LASTNAME_DESC'
}

