name: node

on:
  push:
    branches: ["main"]
    paths:
      - src/ClientApp/**
  pull_request:
    branches: ["main"]
    paths:
      - src/ClientApp/**

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.1
      - name: Install dependencies
        working-directory: src/ClientApp
        run: npm ci
      - name: Lint
        working-directory: src/ClientApp
        run: npm run lint
      - name: Build
        working-directory: src/ClientApp
        run: npm run build
